# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200
  tensorboard_logdir: tblog
  seed: 2337

checkpoint:
  save_interval: 50
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

distributed_training:
  ddp_backend: no_c10d
  find_unused_parameters: true

task:
  _name: audio_pretraining
  data: /private/home/wnhsu/wav2vec2_robust/data/joint_swbd
  normalize: ???
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 1280000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: ${model.freeze_finetune_updates}
  validate_interval: 10000
  validate_interval_updates: 500
  train_subset: train_swbd_10h
  valid_subset: swbd_dev_rt03,ls_dev_other,ted_dev

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 20000
  lr: [8e-5]
  sentence_avg: true
  update_freq: [1]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1,0.0,0.9]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.3
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 5000


hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
  run:
    dir: /checkpoint/wnhsu/experiments/wav2vec2_robust_b1b43cd/finetune/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: /checkpoint/wnhsu/experiments/wav2vec2_robust_b1b43cd/finetune/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}
